# Generated by Django 5.1.2 on 2024-10-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_parcel_content_value_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
